# Usa una imagen base más completa que incluye pip preinstalado
FROM python:3.10

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY . /app/

# Actualiza pip e instala las dependencias
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Exponer el puerto dinámico
EXPOSE $PORT

# Define el comando de inicio
CMD ["gunicorn", "dashboard_corrected:app.server", "--workers=4", "--bind", "0.0.0.0:$PORT"]

