[phases.setup]
runtime = "python@3.10"

[phases.install]
# Asegura que pip esté disponible e instala las dependencias
cmds = ["python -m ensurepip", "pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
# Comando para iniciar la aplicación
cmd = "gunicorn dashboard_corrected:app.server --workers=4 --bind 0.0.0.0:$PORT"
