[phases.setup]
runtime = "python@3.10"

[phases.start]
cmd = "gunicorn dashboard_corrected:app.server --workers=4 --bind 0.0.0.0:$PORT"


[phases.start]
# Comando para iniciar la aplicación usando Gunicorn
cmd = "gunicorn dashboard_corrected:app.server --workers=4 --bind 0.0.0.0:$PORT"

