[phases.setup]
runtime = "python@3.10"

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn dashboard_corrected:app.server --workers=4 --bind 0.0.0.0:$PORT"
